"""Parity with the functions in legacy/ (variant="repo"), on cases where the legacy code is correct: graphs generated by the
legacy code; oracle without tau_max (the legacy oracle is wrong with tau_max); finite-data Fisher-z also with tau_max."""
import io
import contextlib

import numpy as np
import pytest

from itpd import ci, graphs, itpd as I
from itpd import method_runner as runlib

from legacy_modules import legacy_itpd, legacy_itpd_naive

ALPHA = 0.01


def _perm(N, T):
    """legacy (variable-major) index -> new (time-major) column order: new col t*N+n holds legacy n*T+t."""
    return np.array([n * T + t for t in range(T) for n in range(N)])


def _legacy_graph(N, T, max_children, seed):
    np.random.seed(seed)
    u = legacy_itpd.Utils()
    with contextlib.redirect_stdout(io.StringIO()):
        df, p2c, c2p, G, true_adj = u.get_data(M=60, T=T, N=N, max_children=max_children, plot=False)
    return df, true_adj


def _run_legacy(kind, df, var_names, test, true_adj=None, tau_max=None):
    with contextlib.redirect_stdout(io.StringIO()):
        if kind == "itpd":
            m = legacy_itpd.ITPD(df, var_names, independence_test=test, alpha=ALPHA, tau_max=tau_max, true_adj=true_adj)
            m.itpd()
        else:
            m = legacy_itpd_naive.ITPDNaive(df, var_names, independence_test=test, alpha=ALPHA, tau_max=tau_max,
                                       true_adj=true_adj)
            m.itpd_naive()
    return m


@pytest.mark.parametrize("seed", range(12))
def test_oracle_parity_with_legacy(seed):
    rng = np.random.default_rng(seed)
    N, T, mc = int(rng.integers(2, 5)), int(rng.integers(4, 7)), int(rng.integers(1, 4))
    df, true_adj = _legacy_graph(N, T, mc, seed)
    names = [c.split("_")[0] for c in df.columns[::T]]
    p = _perm(N, T)
    A = true_adj[np.ix_(p, p)] != 0
    g = graphs.TimeGraph(A=A, N=N, T=T, tau=T)
    for kind, method, order in (("itpd", "itpd", "variable"), ("naive", "itpd_naive", "time")):
        old = _run_legacy(kind, df, names, "oracle", true_adj=true_adj)
        old_adj = (old.itpd_adj if kind == "itpd" else old.itpd_adj)[np.ix_(p, p)]
        new_cache_none = runlib.run_s2_method(method, None, graph=g, variant="repo", order=order, cache="none")
        new_pair = runlib.run_s2_method(method, None, graph=g, variant="repo", order=order, cache="pair")
        res = I.run_s2(ci.Recorder(ci.DSepCI(g.A), cache="pair"), N, T, ALPHA, reuse=(kind == "itpd"),
                       variant="repo", order=order)
        assert (res.A_hat == old_adj).all()
        assert new_cache_none["metrics"]["exact"] and np.array_equal(old_adj != 0, A)
        # old total_tests = per-pair raw calls (marginals memoized per pair)
        assert [r["raw"] for r in res.per_pair] == list(old.total_tests)
        assert new_cache_none["tests"]["raw_calls"] == sum(old.total_tests)
        # a conditional test can repeat inside one pair (adjacency with S = {X} equals the Z5,7 test), so the
        # per-pair-cache evaluation count is at most the legacy count, which counts every call
        assert new_pair["tests"]["raw_calls"] == sum(old.total_tests)
        assert new_pair["tests"]["evaluated"] <= sum(old.total_tests)


@pytest.mark.parametrize("seed", range(6))
@pytest.mark.parametrize("tau_max", [None, 2])
def test_fisherz_parity_with_legacy(seed, tau_max):
    N, T = 3, 5
    df, _ = _legacy_graph(N, T, 2, 100 + seed)
    names = [c.split("_")[0] for c in df.columns[::T]]
    cols = [f"{names[n]}_{t}" for t in range(T) for n in range(N)]
    data = df[cols].to_numpy()
    for kind, method, order in (("itpd", "itpd", "variable"), ("naive", "itpd_naive", "time")):
        old = _run_legacy(kind, df, names, "fisherz", tau_max=tau_max)
        p = _perm(N, T)
        old_adj = old.itpd_adj[np.ix_(p, p)]
        rec = ci.Recorder(ci.FisherZ(data), cache="none")
        res = I.run_s2(rec, N, T, ALPHA, reuse=(kind == "itpd"), tau_max=tau_max, variant="repo", order=order)
        assert (res.A_hat == old_adj).all(), (kind, seed, tau_max)
        assert [r["raw"] for r in res.per_pair] == list(old.total_tests)
